controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_7
  - name: fake_base_controller
    type: $(arg fake_execution_type)
    joints:
      - wheel_left_joint
      - wheel_right_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: zero
  - group: gripper
    pose: close