# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: zero

# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01

# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - arm_joint
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_7
    - joint_8
  sim_control_mode: 1  # 0: position, 1: velocity

# Publish all joint states
# Creates the /joint_states topic necessary in ROS
grace_arm:  
  arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    gains:
      joint_1: { p: 100, d: 1, i: 1, i_clamp: 1}
      joint_2: { p: 100, d: 1, i: 1, i_clamp: 1}
      joint_3: { p: 100, d: 1, i: 1, i_clamp: 1}
      joint_4: { p: 100, d: 1, i: 1, i_clamp: 1}
      joint_5: { p: 100, d: 1, i: 1, i_clamp: 1}
      joint_6: { p: 100, d: 1, i: 1, i_clamp: 1}
  
  gripper_controller:
    type: "position_controllers/GripperActionController"
    joint: "joint_7"
    command_topic: "gripper_controller/command"
    allow_failure: false
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0
    gains:
      p: 100.0
      i: 0.0
      d: 0.0
      i_clamp: 0.0

controller_list:
  - name: grace_arm/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: grace_arm/gripper_controller
    action_ns: gripper_action
    type: position_controllers/GripperActionController
    joint: joint_7